.if n \{\
.	ds ct "
.\}
.if t \{\
.	ds ct \\(co
.\}
.TH MESSAGES 1L "Melm Version 2.6" "Melm Project"
.SH NAME
messages - quick count of messages in mailbox or folder
.SH SYNOPSIS
.B messages
.br
.B messages
folder-name
.SH DESCRIPTION
.I Messages
counts the occurrences of "^From\ " in either the current incoming 
mailbox or the specified folder.
.P
This is, in fact, a simple little shell script!!
.SH AUTHOR
Melm Project, Elm Development Group
.SH SEE ALSO
from(1L), elm(1L)
.SH BUGS

.SH COPYRIGHTS
\fB\*(ct\fRCopyright 2023-present by the Melm Project
.br
\fB\*(ct\fRCopyright 1988-1995 by The USENET Community Trust
.br
Derived from Elm 2.5, \fB\*(ct\fR Copyright 1986, 1987 by Dave Taylor
